name: Fetch wgcf latest version

on:
  workflow_dispatch:
  schedule:
    - cron: 30 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checking and fetching wgcf latest version
        run: |
          wget -N https://raw.githubusercontent.com/Misaka-blog/Misaka-WARP-Script/master/.github/wgcf.sh
          bash wgcf.sh
      - name: Git uploading
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Uploaded by Github Actions"
          git push
      - name: Refreshing Jsdelivr
        run: |
          curl https://purge.jsdelivr.net/gh/Misaka-blog/Misaka-WARP-Script/files/wgcf_latest_linux_386
          curl https://purge.jsdelivr.net/gh/Misaka-blog/Misaka-WARP-Script/files/wgcf_latest_linux_amd64
          curl https://purge.jsdelivr.net/gh/Misaka-blog/Misaka-WARP-Script/files/wgcf_latest_linux_armv5
          curl https://purge.jsdelivr.net/gh/Misaka-blog/Misaka-WARP-Script/files/wgcf_latest_linux_armv6
          curl https://purge.jsdelivr.net/gh/Misaka-blog/Misaka-WARP-Script/files/wgcf_latest_linux_armv7
          curl https://purge.jsdelivr.net/gh/Misaka-blog/Misaka-WARP-Script/files/wgcf_latest_linux_arm64
          curl https://purge.jsdelivr.net/gh/Misaka-blog/Misaka-WARP-Script/files/wgcf_latest_linux_s390x
